"""SQLAlchemy models. GENERATED by analysis/scripts/gen_models.py. Do not edit by hand."""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any

from sqlalchemy import ARRAY, Boolean, DateTime, Float, Integer, Numeric, String, TypeDecorator
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def new_id() -> str:
    """Client-side id. Prisma generates cuid() client-side too, so no DB default exists."""
    return "c" + uuid.uuid4().hex[:24]


class UTCDateTime(TypeDecorator):
    """Prisma stores DateTime as timestamp(3) without a zone, always UTC.

    Bind: aware datetimes are converted to naive UTC. Result: naive values get UTC attached."""

    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Any) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetime passed to a UTC column; use timezone-aware UTC")
        return value.astimezone(timezone.utc).replace(tzinfo=None)

    def process_result_value(self, value: datetime | None, dialect: Any) -> datetime | None:
        return None if value is None else value.replace(tzinfo=timezone.utc)


class Base(DeclarativeBase):
    pass


class Role(str, enum.Enum):
    EMPLOYEE = "EMPLOYEE"
    ADMIN = "ADMIN"


class ExpenseStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    HELD = "HELD"
    DECLINED = "DECLINED"
    REIMBURSED = "REIMBURSED"


class TimesheetStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"


class Severity(str, enum.Enum):
    IMMEDIATE_HOLD = "IMMEDIATE_HOLD"
    CASE = "CASE"
    NOTE = "NOTE"


class CaseStatus(str, enum.Enum):
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    ESCALATED = "ESCALATED"


class Organization(Base):
    __tablename__ = "Organization"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column("name", String)
    headcount: Mapped[int] = mapped_column("headcount", Integer)


class User(Base):
    __tablename__ = "User"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    org_id: Mapped[str] = mapped_column("orgId", String)
    email: Mapped[str] = mapped_column("email", String, unique=True)
    password_hash: Mapped[str] = mapped_column("passwordHash", String)
    name: Mapped[str] = mapped_column("name", String)
    role: Mapped[Role] = mapped_column("role", SAEnum(Role, name="Role", create_type=False))
    department: Mapped[str] = mapped_column("department", String)
    job_title: Mapped[str] = mapped_column("jobTitle", String)
    manager_id: Mapped[str | None] = mapped_column("managerId", String, nullable=True)
    start_date: Mapped[datetime] = mapped_column("startDate", UTCDateTime)


class Expense(Base):
    __tablename__ = "Expense"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column("userId", String)
    submitted_at: Mapped[datetime] = mapped_column("submittedAt", UTCDateTime)
    incurred_at: Mapped[datetime] = mapped_column("incurredAt", UTCDateTime)
    merchant_raw: Mapped[str] = mapped_column("merchantRaw", String)
    merchant_id: Mapped[str | None] = mapped_column("merchantId", String, nullable=True)
    category_id: Mapped[str] = mapped_column("categoryId", String)
    amount_cents: Mapped[int] = mapped_column("amountCents", Integer)
    currency: Mapped[str] = mapped_column("currency", String, default="USD")
    description: Mapped[str] = mapped_column("description", String)
    receipt_id: Mapped[str | None] = mapped_column("receiptId", String, nullable=True)
    status: Mapped[ExpenseStatus] = mapped_column("status", SAEnum(ExpenseStatus, name="ExpenseStatus", create_type=False))
    extraction: Mapped[Any | None] = mapped_column("extraction", JSONB, nullable=True)


class Receipt(Base):
    __tablename__ = "Receipt"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    uploaded_by_id: Mapped[str] = mapped_column("uploadedById", String)
    storage_key: Mapped[str] = mapped_column("storageKey", String)
    sha256: Mapped[str] = mapped_column("sha256", String)
    phash: Mapped[str] = mapped_column("phash", String)
    mime_type: Mapped[str] = mapped_column("mimeType", String)
    extracted_at: Mapped[datetime | None] = mapped_column("extractedAt", UTCDateTime, nullable=True)
    embedding: Mapped[list[float]] = mapped_column("embedding", ARRAY(Float))


class Timesheet(Base):
    __tablename__ = "Timesheet"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column("userId", String)
    week_start: Mapped[datetime] = mapped_column("weekStart", UTCDateTime)
    submitted_at: Mapped[datetime] = mapped_column("submittedAt", UTCDateTime)
    status: Mapped[TimesheetStatus] = mapped_column("status", SAEnum(TimesheetStatus, name="TimesheetStatus", create_type=False))


class TimesheetEntry(Base):
    __tablename__ = "TimesheetEntry"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    timesheet_id: Mapped[str] = mapped_column("timesheetId", String)
    work_date: Mapped[datetime] = mapped_column("workDate", UTCDateTime)
    start_time: Mapped[datetime | None] = mapped_column("startTime", UTCDateTime, nullable=True)
    end_time: Mapped[datetime | None] = mapped_column("endTime", UTCDateTime, nullable=True)
    hours: Mapped[Decimal] = mapped_column("hours", Numeric(4, 2))
    project: Mapped[str | None] = mapped_column("project", String, nullable=True)
    location: Mapped[str | None] = mapped_column("location", String, nullable=True)
    note: Mapped[str | None] = mapped_column("note", String, nullable=True)


class Merchant(Base):
    __tablename__ = "Merchant"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    org_id: Mapped[str] = mapped_column("orgId", String)
    canonical_name: Mapped[str] = mapped_column("canonicalName", String)
    category_id: Mapped[str] = mapped_column("categoryId", String)
    embedding: Mapped[list[float]] = mapped_column("embedding", ARRAY(Float))


class MerchantAlias(Base):
    __tablename__ = "MerchantAlias"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    merchant_id: Mapped[str] = mapped_column("merchantId", String)
    alias: Mapped[str] = mapped_column("alias", String)


class Baseline(Base):
    __tablename__ = "Baseline"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    scope_type: Mapped[str] = mapped_column("scopeType", String)
    scope_key: Mapped[str] = mapped_column("scopeKey", String)
    median_cents: Mapped[int | None] = mapped_column("medianCents", Integer, nullable=True)
    mad_cents: Mapped[int | None] = mapped_column("madCents", Integer, nullable=True)
    median_hours: Mapped[Decimal | None] = mapped_column("medianHours", Numeric(65, 30), nullable=True)
    sample_size: Mapped[int] = mapped_column("sampleSize", Integer)
    computed_at: Mapped[datetime] = mapped_column("computedAt", UTCDateTime)


class Finding(Base):
    __tablename__ = "Finding"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    org_id: Mapped[str] = mapped_column("orgId", String)
    rule_id: Mapped[str] = mapped_column("ruleId", String)
    subject_user_id: Mapped[str] = mapped_column("subjectUserId", String)
    expense_ids: Mapped[list[str]] = mapped_column("expenseIds", ARRAY(String))
    timesheet_ids: Mapped[list[str]] = mapped_column("timesheetIds", ARRAY(String))
    receipt_ids: Mapped[list[str]] = mapped_column("receiptIds", ARRAY(String))
    confidence: Mapped[float] = mapped_column("confidence", Float)
    amount_at_risk_cents: Mapped[int] = mapped_column("amountAtRiskCents", Integer)
    severity: Mapped[Severity] = mapped_column("severity", SAEnum(Severity, name="Severity", create_type=False))
    penalty_points: Mapped[float] = mapped_column("penaltyPoints", Float)
    evidence: Mapped[Any] = mapped_column("evidence", JSONB)
    detected_at: Mapped[datetime] = mapped_column("detectedAt", UTCDateTime)


class Case(Base):
    __tablename__ = "Case"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    finding_ids: Mapped[list[str]] = mapped_column("findingIds", ARRAY(String))
    subject_user_id: Mapped[str] = mapped_column("subjectUserId", String)
    status: Mapped[CaseStatus] = mapped_column("status", SAEnum(CaseStatus, name="CaseStatus", create_type=False))
    assigned_to_id: Mapped[str | None] = mapped_column("assignedToId", String, nullable=True)
    opened_at: Mapped[datetime] = mapped_column("openedAt", UTCDateTime)
    closed_at: Mapped[datetime | None] = mapped_column("closedAt", UTCDateTime, nullable=True)
    decision_note: Mapped[str | None] = mapped_column("decisionNote", String, nullable=True)
    brief: Mapped[Any | None] = mapped_column("brief", JSONB, nullable=True)


class Hold(Base):
    __tablename__ = "Hold"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    expense_id: Mapped[str] = mapped_column("expenseId", String)
    finding_id: Mapped[str] = mapped_column("findingId", String)
    placed_at: Mapped[datetime] = mapped_column("placedAt", UTCDateTime)
    released_at: Mapped[datetime | None] = mapped_column("releasedAt", UTCDateTime, nullable=True)
    released_by_id: Mapped[str | None] = mapped_column("releasedById", String, nullable=True)
    reverse_note: Mapped[str | None] = mapped_column("reverseNote", String, nullable=True)


class Score(Base):
    __tablename__ = "Score"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    scope_type: Mapped[str] = mapped_column("scopeType", String)
    scope_key: Mapped[str] = mapped_column("scopeKey", String)
    as_of: Mapped[datetime] = mapped_column("asOf", UTCDateTime)
    value: Mapped[float] = mapped_column("value", Float)
    amount_at_risk_cents: Mapped[int] = mapped_column("amountAtRiskCents", Integer)


class ScoreEvent(Base):
    __tablename__ = "ScoreEvent"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    scope_type: Mapped[str] = mapped_column("scopeType", String)
    scope_key: Mapped[str] = mapped_column("scopeKey", String)
    finding_id: Mapped[str | None] = mapped_column("findingId", String, nullable=True)
    delta: Mapped[float] = mapped_column("delta", Float)
    reason: Mapped[str] = mapped_column("reason", String)
    created_at: Mapped[datetime] = mapped_column("createdAt", UTCDateTime)


class Notification(Base):
    __tablename__ = "Notification"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column("userId", String)
    kind: Mapped[str] = mapped_column("kind", String)
    title: Mapped[str] = mapped_column("title", String)
    body: Mapped[str] = mapped_column("body", String)
    link_path: Mapped[str] = mapped_column("linkPath", String)
    read_at: Mapped[datetime | None] = mapped_column("readAt", UTCDateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column("createdAt", UTCDateTime)


class AuditLog(Base):
    __tablename__ = "AuditLog"

    id: Mapped[str] = mapped_column("id", String, primary_key=True, default=new_id)
    actor_id: Mapped[str] = mapped_column("actorId", String)
    action: Mapped[str] = mapped_column("action", String)
    target_type: Mapped[str] = mapped_column("targetType", String)
    target_id: Mapped[str] = mapped_column("targetId", String)
    before: Mapped[Any | None] = mapped_column("before", JSONB, nullable=True)
    after: Mapped[Any | None] = mapped_column("after", JSONB, nullable=True)
    is_self_review: Mapped[bool] = mapped_column("isSelfReview", Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column("createdAt", UTCDateTime)
