"""Generate analysis/app/models.py from web/prisma/schema.prisma.

The Prisma schema is the single source of truth. Run after every schema change:

    python analysis/scripts/gen_models.py

Column names match Prisma exactly (camelCase, quoted) so both services read the same
tables. Python attributes are snake_case.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "web" / "prisma" / "schema.prisma"
OUT = ROOT / "analysis" / "app" / "models.py"

SCALARS = {
    "String": "String",
    "Int": "Integer",
    "Float": "Float",
    "Boolean": "Boolean",
    "DateTime": "UTCDateTime",
    "Json": "JSONB",
}


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def parse(text: str):
    enums: dict[str, list[str]] = {}
    models: dict[str, list[dict]] = {}
    for kind, name, body in re.findall(r"^(enum|model)\s+(\w+)\s*\{(.*?)^\}", text, re.M | re.S):
        lines = [ln.split("//")[0].strip() for ln in body.splitlines()]
        lines = [ln for ln in lines if ln]
        if kind == "enum":
            enums[name] = lines
            continue
        fields = []
        for ln in lines:
            if ln.startswith("@@"):
                continue
            m = re.match(r"(\w+)\s+(\w+)(\[\])?(\?)?\s*(.*)", ln)
            if not m:
                continue
            fname, ftype, is_list, optional, rest = m.groups()
            fields.append(
                {
                    "name": fname,
                    "type": ftype,
                    "list": bool(is_list),
                    "optional": bool(optional),
                    "attrs": rest,
                }
            )
        models[name] = fields
    return enums, models


def column_type(field: dict, enums: dict, models: dict) -> str | None:
    t = field["type"]
    if field["list"]:
        if t in models:  # relation list, not a column
            return None
        return f"ARRAY({SCALARS[t]})"
    if t in models:  # relation object, not a column
        return None
    if t in enums:
        return f'SAEnum({t}, name="{t}", create_type=False)'
    if t == "Decimal":
        m = re.search(r"@db\.Decimal\((\d+),\s*(\d+)\)", field["attrs"])
        p, s = (m.group(1), m.group(2)) if m else ("65", "30")
        return f"Numeric({p}, {s})"
    return SCALARS[t]


def py_type(field: dict, enums: dict) -> str:
    t = field["type"]
    if field["list"]:
        base = f"list[{'float' if t == 'Float' else 'str'}]"
    elif t in enums:
        base = t
    else:
        base = {
            "String": "str",
            "Int": "int",
            "Float": "float",
            "Boolean": "bool",
            "DateTime": "datetime",
            "Json": "Any",
            "Decimal": "Decimal",
        }[t]
    return f"{base} | None" if field["optional"] else base


def main() -> int:
    enums, models = parse(SCHEMA.read_text(encoding="utf-8"))
    out = [
        '"""SQLAlchemy models. GENERATED by analysis/scripts/gen_models.py. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "import enum",
        "import uuid",
        "from datetime import datetime, timezone",
        "from decimal import Decimal",
        "from typing import Any",
        "",
        "from sqlalchemy import ARRAY, Boolean, DateTime, Float, Integer, Numeric, String, TypeDecorator",
        "from sqlalchemy import Enum as SAEnum",
        "from sqlalchemy.dialects.postgresql import JSONB",
        "from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column",
        "",
        "",
        "def new_id() -> str:",
        '    """Client-side id. Prisma generates cuid() client-side too, so no DB default exists."""',
        '    return "c" + uuid.uuid4().hex[:24]',
        "",
        "",
        "class UTCDateTime(TypeDecorator):",
        '    """Prisma stores DateTime as timestamp(3) without a zone, always UTC.',
        "",
        '    Bind: aware datetimes are converted to naive UTC. Result: naive values get UTC attached."""',
        "",
        "    impl = DateTime",
        "    cache_ok = True",
        "",
        "    def process_bind_param(self, value: datetime | None, dialect: Any) -> datetime | None:",
        "        if value is None:",
        "            return None",
        "        if value.tzinfo is None:",
        '            raise ValueError("naive datetime passed to a UTC column; use timezone-aware UTC")',
        "        return value.astimezone(timezone.utc).replace(tzinfo=None)",
        "",
        "    def process_result_value(self, value: datetime | None, dialect: Any) -> datetime | None:",
        "        return None if value is None else value.replace(tzinfo=timezone.utc)",
        "",
        "",
        "class Base(DeclarativeBase):",
        "    pass",
        "",
    ]
    for ename, values in enums.items():
        out += ["", f"class {ename}(str, enum.Enum):"]
        out += [f'    {v} = "{v}"' for v in values]
        out.append("")
    for mname, fields in models.items():
        out += ["", f"class {mname}(Base):", f'    __tablename__ = "{mname}"', ""]
        for f in fields:
            ctype = column_type(f, enums, models)
            if ctype is None:
                continue
            args = [f'"{f["name"]}"', ctype]
            kwargs = []
            if "@id" in f["attrs"]:
                kwargs += ["primary_key=True", "default=new_id"]
            if "@unique" in f["attrs"]:
                kwargs.append("unique=True")
            if f["optional"]:
                kwargs.append("nullable=True")
            m = re.search(r'@default\("([^"]*)"\)', f["attrs"])
            if m:
                kwargs.append(f'default="{m.group(1)}"')
            if "@default(false)" in f["attrs"]:
                kwargs.append("default=False")
            if "@default(true)" in f["attrs"]:
                kwargs.append("default=True")
            out.append(
                f"    {snake(f['name'])}: Mapped[{py_type(f, enums)}] = mapped_column({', '.join(args + kwargs)})"
            )
        out.append("")
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(enums)} enums, {len(models)} models")
    return 0


if __name__ == "__main__":
    sys.exit(main())
